// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edberto/motoclub-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAnnouncementServicer is an autogenerated mock type for the AnnouncementServicer type
type MockAnnouncementServicer struct {
	mock.Mock
}

type MockAnnouncementServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnnouncementServicer) EXPECT() *MockAnnouncementServicer_Expecter {
	return &MockAnnouncementServicer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, title, description
func (_m *MockAnnouncementServicer) Create(ctx context.Context, title string, description string) (domain.Announcement, error) {
	ret := _m.Called(ctx, title, description)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Announcement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Announcement, error)); ok {
		return rf(ctx, title, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Announcement); ok {
		r0 = rf(ctx, title, description)
	} else {
		r0 = ret.Get(0).(domain.Announcement)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnnouncementServicer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAnnouncementServicer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - description string
func (_e *MockAnnouncementServicer_Expecter) Create(ctx interface{}, title interface{}, description interface{}) *MockAnnouncementServicer_Create_Call {
	return &MockAnnouncementServicer_Create_Call{Call: _e.mock.On("Create", ctx, title, description)}
}

func (_c *MockAnnouncementServicer_Create_Call) Run(run func(ctx context.Context, title string, description string)) *MockAnnouncementServicer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAnnouncementServicer_Create_Call) Return(_a0 domain.Announcement, _a1 error) *MockAnnouncementServicer_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnnouncementServicer_Create_Call) RunAndReturn(run func(context.Context, string, string) (domain.Announcement, error)) *MockAnnouncementServicer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAnnouncementServicer) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnnouncementServicer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAnnouncementServicer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAnnouncementServicer_Expecter) Delete(ctx interface{}, id interface{}) *MockAnnouncementServicer_Delete_Call {
	return &MockAnnouncementServicer_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAnnouncementServicer_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockAnnouncementServicer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAnnouncementServicer_Delete_Call) Return(_a0 error) *MockAnnouncementServicer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnnouncementServicer_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockAnnouncementServicer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, startFrom
func (_m *MockAnnouncementServicer) List(ctx context.Context, startFrom *time.Time) ([]domain.Announcement, error) {
	ret := _m.Called(ctx, startFrom)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Announcement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time) ([]domain.Announcement, error)); ok {
		return rf(ctx, startFrom)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time) []domain.Announcement); ok {
		r0 = rf(ctx, startFrom)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Announcement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time) error); ok {
		r1 = rf(ctx, startFrom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnnouncementServicer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAnnouncementServicer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - startFrom *time.Time
func (_e *MockAnnouncementServicer_Expecter) List(ctx interface{}, startFrom interface{}) *MockAnnouncementServicer_List_Call {
	return &MockAnnouncementServicer_List_Call{Call: _e.mock.On("List", ctx, startFrom)}
}

func (_c *MockAnnouncementServicer_List_Call) Run(run func(ctx context.Context, startFrom *time.Time)) *MockAnnouncementServicer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*time.Time))
	})
	return _c
}

func (_c *MockAnnouncementServicer_List_Call) Return(_a0 []domain.Announcement, _a1 error) *MockAnnouncementServicer_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnnouncementServicer_List_Call) RunAndReturn(run func(context.Context, *time.Time) ([]domain.Announcement, error)) *MockAnnouncementServicer_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, title, description
func (_m *MockAnnouncementServicer) Update(ctx context.Context, id int64, title string, description string) (domain.Announcement, error) {
	ret := _m.Called(ctx, id, title, description)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Announcement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) (domain.Announcement, error)); ok {
		return rf(ctx, id, title, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) domain.Announcement); ok {
		r0 = rf(ctx, id, title, description)
	} else {
		r0 = ret.Get(0).(domain.Announcement)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = rf(ctx, id, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnnouncementServicer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAnnouncementServicer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - title string
//   - description string
func (_e *MockAnnouncementServicer_Expecter) Update(ctx interface{}, id interface{}, title interface{}, description interface{}) *MockAnnouncementServicer_Update_Call {
	return &MockAnnouncementServicer_Update_Call{Call: _e.mock.On("Update", ctx, id, title, description)}
}

func (_c *MockAnnouncementServicer_Update_Call) Run(run func(ctx context.Context, id int64, title string, description string)) *MockAnnouncementServicer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAnnouncementServicer_Update_Call) Return(_a0 domain.Announcement, _a1 error) *MockAnnouncementServicer_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnnouncementServicer_Update_Call) RunAndReturn(run func(context.Context, int64, string, string) (domain.Announcement, error)) *MockAnnouncementServicer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnnouncementServicer creates a new instance of MockAnnouncementServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnnouncementServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnnouncementServicer {
	mock := &MockAnnouncementServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
