// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edberto/motoclub-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/edberto/motoclub-backend/internal/service"
)

// MockAuthServicer is an autogenerated mock type for the AuthServicer type
type MockAuthServicer struct {
	mock.Mock
}

type MockAuthServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServicer) EXPECT() *MockAuthServicer_Expecter {
	return &MockAuthServicer_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, googleToken
func (_m *MockAuthServicer) Login(ctx context.Context, email string, googleToken string) (service.LoginResult, error) {
	ret := _m.Called(ctx, email, googleToken)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 service.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (service.LoginResult, error)); ok {
		return rf(ctx, email, googleToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) service.LoginResult); ok {
		r0 = rf(ctx, email, googleToken)
	} else {
		r0 = ret.Get(0).(service.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, googleToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServicer_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - googleToken string
func (_e *MockAuthServicer_Expecter) Login(ctx interface{}, email interface{}, googleToken interface{}) *MockAuthServicer_Login_Call {
	return &MockAuthServicer_Login_Call{Call: _e.mock.On("Login", ctx, email, googleToken)}
}

func (_c *MockAuthServicer_Login_Call) Run(run func(ctx context.Context, email string, googleToken string)) *MockAuthServicer_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthServicer_Login_Call) Return(_a0 service.LoginResult, _a1 error) *MockAuthServicer_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_Login_Call) RunAndReturn(run func(context.Context, string, string) (service.LoginResult, error)) *MockAuthServicer_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, principal
func (_m *MockAuthServicer) Logout(ctx context.Context, principal domain.Principal) error {
	ret := _m.Called(ctx, principal)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Principal) error); ok {
		r0 = rf(ctx, principal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServicer_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.Principal
func (_e *MockAuthServicer_Expecter) Logout(ctx interface{}, principal interface{}) *MockAuthServicer_Logout_Call {
	return &MockAuthServicer_Logout_Call{Call: _e.mock.On("Logout", ctx, principal)}
}

func (_c *MockAuthServicer_Logout_Call) Run(run func(ctx context.Context, principal domain.Principal)) *MockAuthServicer_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Principal))
	})
	return _c
}

func (_c *MockAuthServicer_Logout_Call) Return(_a0 error) *MockAuthServicer_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_Logout_Call) RunAndReturn(run func(context.Context, domain.Principal) error) *MockAuthServicer_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in
func (_m *MockAuthServicer) Register(ctx context.Context, in service.RegisterInput) (domain.Member, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.RegisterInput) (domain.Member, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.RegisterInput) domain.Member); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.RegisterInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServicer_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in service.RegisterInput
func (_e *MockAuthServicer_Expecter) Register(ctx interface{}, in interface{}) *MockAuthServicer_Register_Call {
	return &MockAuthServicer_Register_Call{Call: _e.mock.On("Register", ctx, in)}
}

func (_c *MockAuthServicer_Register_Call) Run(run func(ctx context.Context, in service.RegisterInput)) *MockAuthServicer_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.RegisterInput))
	})
	return _c
}

func (_c *MockAuthServicer_Register_Call) Return(_a0 domain.Member, _a1 error) *MockAuthServicer_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_Register_Call) RunAndReturn(run func(context.Context, service.RegisterInput) (domain.Member, error)) *MockAuthServicer_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServicer creates a new instance of MockAuthServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServicer {
	mock := &MockAuthServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
