// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edberto/motoclub-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/edberto/motoclub-backend/internal/service"

	time "time"
)

// MockEventServicer is an autogenerated mock type for the EventServicer type
type MockEventServicer struct {
	mock.Mock
}

type MockEventServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventServicer) EXPECT() *MockEventServicer_Expecter {
	return &MockEventServicer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockEventServicer) Create(ctx context.Context, in service.EventInput) (domain.Event, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.EventInput) (domain.Event, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.EventInput) domain.Event); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.EventInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventServicer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventServicer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in service.EventInput
func (_e *MockEventServicer_Expecter) Create(ctx interface{}, in interface{}) *MockEventServicer_Create_Call {
	return &MockEventServicer_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockEventServicer_Create_Call) Run(run func(ctx context.Context, in service.EventInput)) *MockEventServicer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.EventInput))
	})
	return _c
}

func (_c *MockEventServicer_Create_Call) Return(_a0 domain.Event, _a1 error) *MockEventServicer_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventServicer_Create_Call) RunAndReturn(run func(context.Context, service.EventInput) (domain.Event, error)) *MockEventServicer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockEventServicer) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventServicer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEventServicer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockEventServicer_Expecter) Delete(ctx interface{}, id interface{}) *MockEventServicer_Delete_Call {
	return &MockEventServicer_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEventServicer_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockEventServicer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockEventServicer_Delete_Call) Return(_a0 error) *MockEventServicer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventServicer_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockEventServicer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id, publicOnly
func (_m *MockEventServicer) Get(ctx context.Context, id int64, publicOnly bool) (domain.Event, error) {
	ret := _m.Called(ctx, id, publicOnly)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) (domain.Event, error)); ok {
		return rf(ctx, id, publicOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) domain.Event); ok {
		r0 = rf(ctx, id, publicOnly)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = rf(ctx, id, publicOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventServicer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEventServicer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - publicOnly bool
func (_e *MockEventServicer_Expecter) Get(ctx interface{}, id interface{}, publicOnly interface{}) *MockEventServicer_Get_Call {
	return &MockEventServicer_Get_Call{Call: _e.mock.On("Get", ctx, id, publicOnly)}
}

func (_c *MockEventServicer_Get_Call) Run(run func(ctx context.Context, id int64, publicOnly bool)) *MockEventServicer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(bool))
	})
	return _c
}

func (_c *MockEventServicer_Get_Call) Return(_a0 domain.Event, _a1 error) *MockEventServicer_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventServicer_Get_Call) RunAndReturn(run func(context.Context, int64, bool) (domain.Event, error)) *MockEventServicer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, startFrom, publicOnly
func (_m *MockEventServicer) List(ctx context.Context, startFrom *time.Time, publicOnly bool) ([]domain.Event, error) {
	ret := _m.Called(ctx, startFrom, publicOnly)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, bool) ([]domain.Event, error)); ok {
		return rf(ctx, startFrom, publicOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, bool) []domain.Event); ok {
		r0 = rf(ctx, startFrom, publicOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, bool) error); ok {
		r1 = rf(ctx, startFrom, publicOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventServicer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventServicer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - startFrom *time.Time
//   - publicOnly bool
func (_e *MockEventServicer_Expecter) List(ctx interface{}, startFrom interface{}, publicOnly interface{}) *MockEventServicer_List_Call {
	return &MockEventServicer_List_Call{Call: _e.mock.On("List", ctx, startFrom, publicOnly)}
}

func (_c *MockEventServicer_List_Call) Run(run func(ctx context.Context, startFrom *time.Time, publicOnly bool)) *MockEventServicer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*time.Time), args[2].(bool))
	})
	return _c
}

func (_c *MockEventServicer_List_Call) Return(_a0 []domain.Event, _a1 error) *MockEventServicer_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventServicer_List_Call) RunAndReturn(run func(context.Context, *time.Time, bool) ([]domain.Event, error)) *MockEventServicer_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, in
func (_m *MockEventServicer) Update(ctx context.Context, id int64, in service.EventInput) (domain.Event, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, service.EventInput) (domain.Event, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, service.EventInput) domain.Event); ok {
		r0 = rf(ctx, id, in)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, service.EventInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventServicer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEventServicer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - in service.EventInput
func (_e *MockEventServicer_Expecter) Update(ctx interface{}, id interface{}, in interface{}) *MockEventServicer_Update_Call {
	return &MockEventServicer_Update_Call{Call: _e.mock.On("Update", ctx, id, in)}
}

func (_c *MockEventServicer_Update_Call) Run(run func(ctx context.Context, id int64, in service.EventInput)) *MockEventServicer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(service.EventInput))
	})
	return _c
}

func (_c *MockEventServicer_Update_Call) Return(_a0 domain.Event, _a1 error) *MockEventServicer_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventServicer_Update_Call) RunAndReturn(run func(context.Context, int64, service.EventInput) (domain.Event, error)) *MockEventServicer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventServicer creates a new instance of MockEventServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventServicer {
	mock := &MockEventServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
