// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edberto/motoclub-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/edberto/motoclub-backend/internal/service"
)

// MockMemberServicer is an autogenerated mock type for the MemberServicer type
type MockMemberServicer struct {
	mock.Mock
}

type MockMemberServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberServicer) EXPECT() *MockMemberServicer_Expecter {
	return &MockMemberServicer_Expecter{mock: &_m.Mock}
}

// CountMembers provides a mock function with given fields: ctx
func (_m *MockMemberServicer) CountMembers(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountMembers")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberServicer_CountMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMembers'
type MockMemberServicer_CountMembers_Call struct {
	*mock.Call
}

// CountMembers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberServicer_Expecter) CountMembers(ctx interface{}) *MockMemberServicer_CountMembers_Call {
	return &MockMemberServicer_CountMembers_Call{Call: _e.mock.On("CountMembers", ctx)}
}

func (_c *MockMemberServicer_CountMembers_Call) Run(run func(ctx context.Context)) *MockMemberServicer_CountMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberServicer_CountMembers_Call) Return(_a0 int64, _a1 error) *MockMemberServicer_CountMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberServicer_CountMembers_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockMemberServicer_CountMembers_Call {
	_c.Call.Return(run)
	return _c
}

// CountPending provides a mock function with given fields: ctx
func (_m *MockMemberServicer) CountPending(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountPending")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberServicer_CountPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPending'
type MockMemberServicer_CountPending_Call struct {
	*mock.Call
}

// CountPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberServicer_Expecter) CountPending(ctx interface{}) *MockMemberServicer_CountPending_Call {
	return &MockMemberServicer_CountPending_Call{Call: _e.mock.On("CountPending", ctx)}
}

func (_c *MockMemberServicer_CountPending_Call) Run(run func(ctx context.Context)) *MockMemberServicer_CountPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberServicer_CountPending_Call) Return(_a0 int64, _a1 error) *MockMemberServicer_CountPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberServicer_CountPending_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockMemberServicer_CountPending_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, actor, targetID
func (_m *MockMemberServicer) Delete(ctx context.Context, actor domain.Principal, targetID int64) error {
	ret := _m.Called(ctx, actor, targetID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Principal, int64) error); ok {
		r0 = rf(ctx, actor, targetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberServicer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMemberServicer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - actor domain.Principal
//   - targetID int64
func (_e *MockMemberServicer_Expecter) Delete(ctx interface{}, actor interface{}, targetID interface{}) *MockMemberServicer_Delete_Call {
	return &MockMemberServicer_Delete_Call{Call: _e.mock.On("Delete", ctx, actor, targetID)}
}

func (_c *MockMemberServicer_Delete_Call) Run(run func(ctx context.Context, actor domain.Principal, targetID int64)) *MockMemberServicer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Principal), args[2].(int64))
	})
	return _c
}

func (_c *MockMemberServicer_Delete_Call) Return(_a0 error) *MockMemberServicer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberServicer_Delete_Call) RunAndReturn(run func(context.Context, domain.Principal, int64) error) *MockMemberServicer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, id
func (_m *MockMemberServicer) GetProfile(ctx context.Context, id int64) (domain.Member, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Member, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Member); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberServicer_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockMemberServicer_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockMemberServicer_Expecter) GetProfile(ctx interface{}, id interface{}) *MockMemberServicer_GetProfile_Call {
	return &MockMemberServicer_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, id)}
}

func (_c *MockMemberServicer_GetProfile_Call) Run(run func(ctx context.Context, id int64)) *MockMemberServicer_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMemberServicer_GetProfile_Call) Return(_a0 domain.Member, _a1 error) *MockMemberServicer_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberServicer_GetProfile_Call) RunAndReturn(run func(context.Context, int64) (domain.Member, error)) *MockMemberServicer_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx
func (_m *MockMemberServicer) ListMembers(ctx context.Context) ([]domain.Member, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Member, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Member); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberServicer_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockMemberServicer_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberServicer_Expecter) ListMembers(ctx interface{}) *MockMemberServicer_ListMembers_Call {
	return &MockMemberServicer_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx)}
}

func (_c *MockMemberServicer_ListMembers_Call) Run(run func(ctx context.Context)) *MockMemberServicer_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberServicer_ListMembers_Call) Return(_a0 []domain.Member, _a1 error) *MockMemberServicer_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberServicer_ListMembers_Call) RunAndReturn(run func(context.Context) ([]domain.Member, error)) *MockMemberServicer_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListPending provides a mock function with given fields: ctx
func (_m *MockMemberServicer) ListPending(ctx context.Context) ([]domain.Registration, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []domain.Registration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Registration, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Registration); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Registration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberServicer_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type MockMemberServicer_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberServicer_Expecter) ListPending(ctx interface{}) *MockMemberServicer_ListPending_Call {
	return &MockMemberServicer_ListPending_Call{Call: _e.mock.On("ListPending", ctx)}
}

func (_c *MockMemberServicer_ListPending_Call) Run(run func(ctx context.Context)) *MockMemberServicer_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberServicer_ListPending_Call) Return(_a0 []domain.Registration, _a1 error) *MockMemberServicer_ListPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberServicer_ListPending_Call) RunAndReturn(run func(context.Context) ([]domain.Registration, error)) *MockMemberServicer_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function with given fields: ctx, id, action, remarks
func (_m *MockMemberServicer) SetStatus(ctx context.Context, id int64, action service.StatusAction, remarks *string) error {
	ret := _m.Called(ctx, id, action, remarks)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, service.StatusAction, *string) error); ok {
		r0 = rf(ctx, id, action, remarks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberServicer_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockMemberServicer_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - action service.StatusAction
//   - remarks *string
func (_e *MockMemberServicer_Expecter) SetStatus(ctx interface{}, id interface{}, action interface{}, remarks interface{}) *MockMemberServicer_SetStatus_Call {
	return &MockMemberServicer_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, id, action, remarks)}
}

func (_c *MockMemberServicer_SetStatus_Call) Run(run func(ctx context.Context, id int64, action service.StatusAction, remarks *string)) *MockMemberServicer_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(service.StatusAction), args[3].(*string))
	})
	return _c
}

func (_c *MockMemberServicer_SetStatus_Call) Return(_a0 error) *MockMemberServicer_SetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberServicer_SetStatus_Call) RunAndReturn(run func(context.Context, int64, service.StatusAction, *string) error) *MockMemberServicer_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, id, role
func (_m *MockMemberServicer) UpdateRole(ctx context.Context, id int64, role domain.Role) error {
	ret := _m.Called(ctx, id, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Role) error); ok {
		r0 = rf(ctx, id, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberServicer_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockMemberServicer_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - role domain.Role
func (_e *MockMemberServicer_Expecter) UpdateRole(ctx interface{}, id interface{}, role interface{}) *MockMemberServicer_UpdateRole_Call {
	return &MockMemberServicer_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, id, role)}
}

func (_c *MockMemberServicer_UpdateRole_Call) Run(run func(ctx context.Context, id int64, role domain.Role)) *MockMemberServicer_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Role))
	})
	return _c
}

func (_c *MockMemberServicer_UpdateRole_Call) Return(_a0 error) *MockMemberServicer_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberServicer_UpdateRole_Call) RunAndReturn(run func(context.Context, int64, domain.Role) error) *MockMemberServicer_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberServicer creates a new instance of MockMemberServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberServicer {
	mock := &MockMemberServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
