// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSiteContentServicer is an autogenerated mock type for the SiteContentServicer type
type MockSiteContentServicer struct {
	mock.Mock
}

type MockSiteContentServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSiteContentServicer) EXPECT() *MockSiteContentServicer_Expecter {
	return &MockSiteContentServicer_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx
func (_m *MockSiteContentServicer) Get(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiteContentServicer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSiteContentServicer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSiteContentServicer_Expecter) Get(ctx interface{}) *MockSiteContentServicer_Get_Call {
	return &MockSiteContentServicer_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockSiteContentServicer_Get_Call) Run(run func(ctx context.Context)) *MockSiteContentServicer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSiteContentServicer_Get_Call) Return(_a0 []byte, _a1 error) *MockSiteContentServicer_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiteContentServicer_Get_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockSiteContentServicer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, data
func (_m *MockSiteContentServicer) Update(ctx context.Context, data []byte) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiteContentServicer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSiteContentServicer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockSiteContentServicer_Expecter) Update(ctx interface{}, data interface{}) *MockSiteContentServicer_Update_Call {
	return &MockSiteContentServicer_Update_Call{Call: _e.mock.On("Update", ctx, data)}
}

func (_c *MockSiteContentServicer_Update_Call) Run(run func(ctx context.Context, data []byte)) *MockSiteContentServicer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockSiteContentServicer_Update_Call) Return(_a0 error) *MockSiteContentServicer_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiteContentServicer_Update_Call) RunAndReturn(run func(context.Context, []byte) error) *MockSiteContentServicer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSiteContentServicer creates a new instance of MockSiteContentServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSiteContentServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSiteContentServicer {
	mock := &MockSiteContentServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
