// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edberto/motoclub-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAnnouncementRepository is an autogenerated mock type for the AnnouncementRepository type
type MockAnnouncementRepository struct {
	mock.Mock
}

type MockAnnouncementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnnouncementRepository) EXPECT() *MockAnnouncementRepository_Expecter {
	return &MockAnnouncementRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx
func (_m *MockAnnouncementRepository) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnnouncementRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockAnnouncementRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAnnouncementRepository_Expecter) Count(ctx interface{}) *MockAnnouncementRepository_Count_Call {
	return &MockAnnouncementRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockAnnouncementRepository_Count_Call) Run(run func(ctx context.Context)) *MockAnnouncementRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAnnouncementRepository_Count_Call) Return(_a0 int64, _a1 error) *MockAnnouncementRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnnouncementRepository_Count_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockAnnouncementRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, title, description, isPublic
func (_m *MockAnnouncementRepository) Create(ctx context.Context, title string, description string, isPublic bool) (domain.Announcement, error) {
	ret := _m.Called(ctx, title, description, isPublic)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Announcement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (domain.Announcement, error)); ok {
		return rf(ctx, title, description, isPublic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) domain.Announcement); ok {
		r0 = rf(ctx, title, description, isPublic)
	} else {
		r0 = ret.Get(0).(domain.Announcement)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, title, description, isPublic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnnouncementRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAnnouncementRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - description string
//   - isPublic bool
func (_e *MockAnnouncementRepository_Expecter) Create(ctx interface{}, title interface{}, description interface{}, isPublic interface{}) *MockAnnouncementRepository_Create_Call {
	return &MockAnnouncementRepository_Create_Call{Call: _e.mock.On("Create", ctx, title, description, isPublic)}
}

func (_c *MockAnnouncementRepository_Create_Call) Run(run func(ctx context.Context, title string, description string, isPublic bool)) *MockAnnouncementRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockAnnouncementRepository_Create_Call) Return(_a0 domain.Announcement, _a1 error) *MockAnnouncementRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnnouncementRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, bool) (domain.Announcement, error)) *MockAnnouncementRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, startFrom, publicOnly
func (_m *MockAnnouncementRepository) List(ctx context.Context, startFrom *time.Time, publicOnly bool) ([]domain.Announcement, error) {
	ret := _m.Called(ctx, startFrom, publicOnly)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Announcement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, bool) ([]domain.Announcement, error)); ok {
		return rf(ctx, startFrom, publicOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, bool) []domain.Announcement); ok {
		r0 = rf(ctx, startFrom, publicOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Announcement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, bool) error); ok {
		r1 = rf(ctx, startFrom, publicOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnnouncementRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAnnouncementRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - startFrom *time.Time
//   - publicOnly bool
func (_e *MockAnnouncementRepository_Expecter) List(ctx interface{}, startFrom interface{}, publicOnly interface{}) *MockAnnouncementRepository_List_Call {
	return &MockAnnouncementRepository_List_Call{Call: _e.mock.On("List", ctx, startFrom, publicOnly)}
}

func (_c *MockAnnouncementRepository_List_Call) Run(run func(ctx context.Context, startFrom *time.Time, publicOnly bool)) *MockAnnouncementRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*time.Time), args[2].(bool))
	})
	return _c
}

func (_c *MockAnnouncementRepository_List_Call) Return(_a0 []domain.Announcement, _a1 error) *MockAnnouncementRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnnouncementRepository_List_Call) RunAndReturn(run func(context.Context, *time.Time, bool) ([]domain.Announcement, error)) *MockAnnouncementRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockAnnouncementRepository) SoftDelete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnnouncementRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockAnnouncementRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAnnouncementRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockAnnouncementRepository_SoftDelete_Call {
	return &MockAnnouncementRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockAnnouncementRepository_SoftDelete_Call) Run(run func(ctx context.Context, id int64)) *MockAnnouncementRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAnnouncementRepository_SoftDelete_Call) Return(_a0 error) *MockAnnouncementRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnnouncementRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, int64) error) *MockAnnouncementRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, title, description, isPublic
func (_m *MockAnnouncementRepository) Update(ctx context.Context, id int64, title string, description string, isPublic bool) (domain.Announcement, error) {
	ret := _m.Called(ctx, id, title, description, isPublic)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Announcement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, bool) (domain.Announcement, error)); ok {
		return rf(ctx, id, title, description, isPublic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, bool) domain.Announcement); ok {
		r0 = rf(ctx, id, title, description, isPublic)
	} else {
		r0 = ret.Get(0).(domain.Announcement)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, bool) error); ok {
		r1 = rf(ctx, id, title, description, isPublic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnnouncementRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAnnouncementRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - title string
//   - description string
//   - isPublic bool
func (_e *MockAnnouncementRepository_Expecter) Update(ctx interface{}, id interface{}, title interface{}, description interface{}, isPublic interface{}) *MockAnnouncementRepository_Update_Call {
	return &MockAnnouncementRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, title, description, isPublic)}
}

func (_c *MockAnnouncementRepository_Update_Call) Run(run func(ctx context.Context, id int64, title string, description string, isPublic bool)) *MockAnnouncementRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockAnnouncementRepository_Update_Call) Return(_a0 domain.Announcement, _a1 error) *MockAnnouncementRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnnouncementRepository_Update_Call) RunAndReturn(run func(context.Context, int64, string, string, bool) (domain.Announcement, error)) *MockAnnouncementRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnnouncementRepository creates a new instance of MockAnnouncementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnnouncementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnnouncementRepository {
	mock := &MockAnnouncementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
