// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edberto/motoclub-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/edberto/motoclub-backend/internal/repository"

	time "time"
)

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockEventRepository) Create(ctx context.Context, in repository.CreateEventInput) (domain.Event, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateEventInput) (domain.Event, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateEventInput) domain.Event); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateEventInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.CreateEventInput
func (_e *MockEventRepository_Expecter) Create(ctx interface{}, in interface{}) *MockEventRepository_Create_Call {
	return &MockEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockEventRepository_Create_Call) Run(run func(ctx context.Context, in repository.CreateEventInput)) *MockEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateEventInput))
	})
	return _c
}

func (_c *MockEventRepository_Create_Call) Return(_a0 domain.Event, _a1 error) *MockEventRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventRepository_Create_Call) RunAndReturn(run func(context.Context, repository.CreateEventInput) (domain.Event, error)) *MockEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, publicOnly
func (_m *MockEventRepository) GetByID(ctx context.Context, id int64, publicOnly bool) (domain.Event, error) {
	ret := _m.Called(ctx, id, publicOnly)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) (domain.Event, error)); ok {
		return rf(ctx, id, publicOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) domain.Event); ok {
		r0 = rf(ctx, id, publicOnly)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = rf(ctx, id, publicOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockEventRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - publicOnly bool
func (_e *MockEventRepository_Expecter) GetByID(ctx interface{}, id interface{}, publicOnly interface{}) *MockEventRepository_GetByID_Call {
	return &MockEventRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, publicOnly)}
}

func (_c *MockEventRepository_GetByID_Call) Run(run func(ctx context.Context, id int64, publicOnly bool)) *MockEventRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(bool))
	})
	return _c
}

func (_c *MockEventRepository_GetByID_Call) Return(_a0 domain.Event, _a1 error) *MockEventRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64, bool) (domain.Event, error)) *MockEventRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, startFrom, publicOnly
func (_m *MockEventRepository) List(ctx context.Context, startFrom *time.Time, publicOnly bool) ([]domain.Event, error) {
	ret := _m.Called(ctx, startFrom, publicOnly)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, bool) ([]domain.Event, error)); ok {
		return rf(ctx, startFrom, publicOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, bool) []domain.Event); ok {
		r0 = rf(ctx, startFrom, publicOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, bool) error); ok {
		r1 = rf(ctx, startFrom, publicOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - startFrom *time.Time
//   - publicOnly bool
func (_e *MockEventRepository_Expecter) List(ctx interface{}, startFrom interface{}, publicOnly interface{}) *MockEventRepository_List_Call {
	return &MockEventRepository_List_Call{Call: _e.mock.On("List", ctx, startFrom, publicOnly)}
}

func (_c *MockEventRepository_List_Call) Run(run func(ctx context.Context, startFrom *time.Time, publicOnly bool)) *MockEventRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*time.Time), args[2].(bool))
	})
	return _c
}

func (_c *MockEventRepository_List_Call) Return(_a0 []domain.Event, _a1 error) *MockEventRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventRepository_List_Call) RunAndReturn(run func(context.Context, *time.Time, bool) ([]domain.Event, error)) *MockEventRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockEventRepository) SoftDelete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockEventRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockEventRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockEventRepository_SoftDelete_Call {
	return &MockEventRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockEventRepository_SoftDelete_Call) Run(run func(ctx context.Context, id int64)) *MockEventRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockEventRepository_SoftDelete_Call) Return(_a0 error) *MockEventRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, int64) error) *MockEventRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, in
func (_m *MockEventRepository) Update(ctx context.Context, in repository.UpdateEventInput) (domain.Event, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateEventInput) (domain.Event, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateEventInput) domain.Event); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateEventInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.UpdateEventInput
func (_e *MockEventRepository_Expecter) Update(ctx interface{}, in interface{}) *MockEventRepository_Update_Call {
	return &MockEventRepository_Update_Call{Call: _e.mock.On("Update", ctx, in)}
}

func (_c *MockEventRepository_Update_Call) Run(run func(ctx context.Context, in repository.UpdateEventInput)) *MockEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.UpdateEventInput))
	})
	return _c
}

func (_c *MockEventRepository_Update_Call) Return(_a0 domain.Event, _a1 error) *MockEventRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventRepository_Update_Call) RunAndReturn(run func(context.Context, repository.UpdateEventInput) (domain.Event, error)) *MockEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
