// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edberto/motoclub-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockGalleryRepository is an autogenerated mock type for the GalleryRepository type
type MockGalleryRepository struct {
	mock.Mock
}

type MockGalleryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGalleryRepository) EXPECT() *MockGalleryRepository_Expecter {
	return &MockGalleryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, link
func (_m *MockGalleryRepository) Create(ctx context.Context, link string) (domain.GalleryItem, error) {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.GalleryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.GalleryItem, error)); ok {
		return rf(ctx, link)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.GalleryItem); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Get(0).(domain.GalleryItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGalleryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGalleryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - link string
func (_e *MockGalleryRepository_Expecter) Create(ctx interface{}, link interface{}) *MockGalleryRepository_Create_Call {
	return &MockGalleryRepository_Create_Call{Call: _e.mock.On("Create", ctx, link)}
}

func (_c *MockGalleryRepository_Create_Call) Run(run func(ctx context.Context, link string)) *MockGalleryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGalleryRepository_Create_Call) Return(_a0 domain.GalleryItem, _a1 error) *MockGalleryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGalleryRepository_Create_Call) RunAndReturn(run func(context.Context, string) (domain.GalleryItem, error)) *MockGalleryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockGalleryRepository) List(ctx context.Context) ([]domain.GalleryItem, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.GalleryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.GalleryItem, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.GalleryItem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GalleryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGalleryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGalleryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGalleryRepository_Expecter) List(ctx interface{}) *MockGalleryRepository_List_Call {
	return &MockGalleryRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockGalleryRepository_List_Call) Run(run func(ctx context.Context)) *MockGalleryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGalleryRepository_List_Call) Return(_a0 []domain.GalleryItem, _a1 error) *MockGalleryRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGalleryRepository_List_Call) RunAndReturn(run func(context.Context) ([]domain.GalleryItem, error)) *MockGalleryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockGalleryRepository) SoftDelete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGalleryRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockGalleryRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockGalleryRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockGalleryRepository_SoftDelete_Call {
	return &MockGalleryRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockGalleryRepository_SoftDelete_Call) Run(run func(ctx context.Context, id int64)) *MockGalleryRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGalleryRepository_SoftDelete_Call) Return(_a0 error) *MockGalleryRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGalleryRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, int64) error) *MockGalleryRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGalleryRepository creates a new instance of MockGalleryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGalleryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGalleryRepository {
	mock := &MockGalleryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
