// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edberto/motoclub-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/edberto/motoclub-backend/internal/repository"
)

// MockMemberRepository is an autogenerated mock type for the MemberRepository type
type MockMemberRepository struct {
	mock.Mock
}

type MockMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberRepository) EXPECT() *MockMemberRepository_Expecter {
	return &MockMemberRepository_Expecter{mock: &_m.Mock}
}

// BackfillGoogleSub provides a mock function with given fields: ctx, id, googleSub
func (_m *MockMemberRepository) BackfillGoogleSub(ctx context.Context, id int64, googleSub string) (domain.Member, error) {
	ret := _m.Called(ctx, id, googleSub)

	if len(ret) == 0 {
		panic("no return value specified for BackfillGoogleSub")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (domain.Member, error)); ok {
		return rf(ctx, id, googleSub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) domain.Member); ok {
		r0 = rf(ctx, id, googleSub)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, id, googleSub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_BackfillGoogleSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackfillGoogleSub'
type MockMemberRepository_BackfillGoogleSub_Call struct {
	*mock.Call
}

// BackfillGoogleSub is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - googleSub string
func (_e *MockMemberRepository_Expecter) BackfillGoogleSub(ctx interface{}, id interface{}, googleSub interface{}) *MockMemberRepository_BackfillGoogleSub_Call {
	return &MockMemberRepository_BackfillGoogleSub_Call{Call: _e.mock.On("BackfillGoogleSub", ctx, id, googleSub)}
}

func (_c *MockMemberRepository_BackfillGoogleSub_Call) Run(run func(ctx context.Context, id int64, googleSub string)) *MockMemberRepository_BackfillGoogleSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockMemberRepository_BackfillGoogleSub_Call) Return(_a0 domain.Member, _a1 error) *MockMemberRepository_BackfillGoogleSub_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_BackfillGoogleSub_Call) RunAndReturn(run func(context.Context, int64, string) (domain.Member, error)) *MockMemberRepository_BackfillGoogleSub_Call {
	_c.Call.Return(run)
	return _c
}

// CountPending provides a mock function with given fields: ctx
func (_m *MockMemberRepository) CountPending(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountPending")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_CountPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPending'
type MockMemberRepository_CountPending_Call struct {
	*mock.Call
}

// CountPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberRepository_Expecter) CountPending(ctx interface{}) *MockMemberRepository_CountPending_Call {
	return &MockMemberRepository_CountPending_Call{Call: _e.mock.On("CountPending", ctx)}
}

func (_c *MockMemberRepository_CountPending_Call) Run(run func(ctx context.Context)) *MockMemberRepository_CountPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberRepository_CountPending_Call) Return(_a0 int64, _a1 error) *MockMemberRepository_CountPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_CountPending_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockMemberRepository_CountPending_Call {
	_c.Call.Return(run)
	return _c
}

// CountSuperadmins provides a mock function with given fields: ctx
func (_m *MockMemberRepository) CountSuperadmins(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountSuperadmins")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_CountSuperadmins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSuperadmins'
type MockMemberRepository_CountSuperadmins_Call struct {
	*mock.Call
}

// CountSuperadmins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberRepository_Expecter) CountSuperadmins(ctx interface{}) *MockMemberRepository_CountSuperadmins_Call {
	return &MockMemberRepository_CountSuperadmins_Call{Call: _e.mock.On("CountSuperadmins", ctx)}
}

func (_c *MockMemberRepository_CountSuperadmins_Call) Run(run func(ctx context.Context)) *MockMemberRepository_CountSuperadmins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberRepository_CountSuperadmins_Call) Return(_a0 int64, _a1 error) *MockMemberRepository_CountSuperadmins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_CountSuperadmins_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockMemberRepository_CountSuperadmins_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockMemberRepository) Create(ctx context.Context, in repository.CreateMemberInput) (domain.Member, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateMemberInput) (domain.Member, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateMemberInput) domain.Member); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateMemberInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMemberRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.CreateMemberInput
func (_e *MockMemberRepository_Expecter) Create(ctx interface{}, in interface{}) *MockMemberRepository_Create_Call {
	return &MockMemberRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockMemberRepository_Create_Call) Run(run func(ctx context.Context, in repository.CreateMemberInput)) *MockMemberRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateMemberInput))
	})
	return _c
}

func (_c *MockMemberRepository_Create_Call) Return(_a0 domain.Member, _a1 error) *MockMemberRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_Create_Call) RunAndReturn(run func(context.Context, repository.CreateMemberInput) (domain.Member, error)) *MockMemberRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockMemberRepository) GetByEmail(ctx context.Context, email string) (domain.Member, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Member, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Member); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockMemberRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockMemberRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockMemberRepository_GetByEmail_Call {
	return &MockMemberRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockMemberRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockMemberRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_GetByEmail_Call) Return(_a0 domain.Member, _a1 error) *MockMemberRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.Member, error)) *MockMemberRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGoogleSub provides a mock function with given fields: ctx, googleSub
func (_m *MockMemberRepository) GetByGoogleSub(ctx context.Context, googleSub string) (domain.Member, error) {
	ret := _m.Called(ctx, googleSub)

	if len(ret) == 0 {
		panic("no return value specified for GetByGoogleSub")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Member, error)); ok {
		return rf(ctx, googleSub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Member); ok {
		r0 = rf(ctx, googleSub)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, googleSub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_GetByGoogleSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGoogleSub'
type MockMemberRepository_GetByGoogleSub_Call struct {
	*mock.Call
}

// GetByGoogleSub is a helper method to define mock.On call
//   - ctx context.Context
//   - googleSub string
func (_e *MockMemberRepository_Expecter) GetByGoogleSub(ctx interface{}, googleSub interface{}) *MockMemberRepository_GetByGoogleSub_Call {
	return &MockMemberRepository_GetByGoogleSub_Call{Call: _e.mock.On("GetByGoogleSub", ctx, googleSub)}
}

func (_c *MockMemberRepository_GetByGoogleSub_Call) Run(run func(ctx context.Context, googleSub string)) *MockMemberRepository_GetByGoogleSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_GetByGoogleSub_Call) Return(_a0 domain.Member, _a1 error) *MockMemberRepository_GetByGoogleSub_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_GetByGoogleSub_Call) RunAndReturn(run func(context.Context, string) (domain.Member, error)) *MockMemberRepository_GetByGoogleSub_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMemberRepository) GetByID(ctx context.Context, id int64) (domain.Member, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Member, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Member); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMemberRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockMemberRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockMemberRepository_GetByID_Call {
	return &MockMemberRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMemberRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockMemberRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMemberRepository_GetByID_Call) Return(_a0 domain.Member, _a1 error) *MockMemberRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (domain.Member, error)) *MockMemberRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockMemberRepository) List(ctx context.Context) ([]domain.Member, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Member, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Member); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMemberRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberRepository_Expecter) List(ctx interface{}) *MockMemberRepository_List_Call {
	return &MockMemberRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockMemberRepository_List_Call) Run(run func(ctx context.Context)) *MockMemberRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberRepository_List_Call) Return(_a0 []domain.Member, _a1 error) *MockMemberRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_List_Call) RunAndReturn(run func(context.Context) ([]domain.Member, error)) *MockMemberRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPending provides a mock function with given fields: ctx
func (_m *MockMemberRepository) ListPending(ctx context.Context) ([]domain.Registration, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []domain.Registration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Registration, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Registration); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Registration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type MockMemberRepository_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberRepository_Expecter) ListPending(ctx interface{}) *MockMemberRepository_ListPending_Call {
	return &MockMemberRepository_ListPending_Call{Call: _e.mock.On("ListPending", ctx)}
}

func (_c *MockMemberRepository_ListPending_Call) Run(run func(ctx context.Context)) *MockMemberRepository_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberRepository_ListPending_Call) Return(_a0 []domain.Registration, _a1 error) *MockMemberRepository_ListPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_ListPending_Call) RunAndReturn(run func(context.Context) ([]domain.Registration, error)) *MockMemberRepository_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockMemberRepository) SoftDelete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockMemberRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockMemberRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockMemberRepository_SoftDelete_Call {
	return &MockMemberRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockMemberRepository_SoftDelete_Call) Run(run func(ctx context.Context, id int64)) *MockMemberRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMemberRepository_SoftDelete_Call) Return(_a0 error) *MockMemberRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, int64) error) *MockMemberRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, id, role
func (_m *MockMemberRepository) UpdateRole(ctx context.Context, id int64, role domain.Role) (domain.Member, error) {
	ret := _m.Called(ctx, id, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Role) (domain.Member, error)); ok {
		return rf(ctx, id, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Role) domain.Member); ok {
		r0 = rf(ctx, id, role)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.Role) error); ok {
		r1 = rf(ctx, id, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockMemberRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - role domain.Role
func (_e *MockMemberRepository_Expecter) UpdateRole(ctx interface{}, id interface{}, role interface{}) *MockMemberRepository_UpdateRole_Call {
	return &MockMemberRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, id, role)}
}

func (_c *MockMemberRepository_UpdateRole_Call) Run(run func(ctx context.Context, id int64, role domain.Role)) *MockMemberRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Role))
	})
	return _c
}

func (_c *MockMemberRepository_UpdateRole_Call) Return(_a0 domain.Member, _a1 error) *MockMemberRepository_UpdateRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_UpdateRole_Call) RunAndReturn(run func(context.Context, int64, domain.Role) (domain.Member, error)) *MockMemberRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, in
func (_m *MockMemberRepository) UpdateStatus(ctx context.Context, in repository.UpdateStatusInput) (domain.Member, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateStatusInput) (domain.Member, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateStatusInput) domain.Member); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateStatusInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockMemberRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.UpdateStatusInput
func (_e *MockMemberRepository_Expecter) UpdateStatus(ctx interface{}, in interface{}) *MockMemberRepository_UpdateStatus_Call {
	return &MockMemberRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, in)}
}

func (_c *MockMemberRepository_UpdateStatus_Call) Run(run func(ctx context.Context, in repository.UpdateStatusInput)) *MockMemberRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.UpdateStatusInput))
	})
	return _c
}

func (_c *MockMemberRepository_UpdateStatus_Call) Return(_a0 domain.Member, _a1 error) *MockMemberRepository_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, repository.UpdateStatusInput) (domain.Member, error)) *MockMemberRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberRepository creates a new instance of MockMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberRepository {
	mock := &MockMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
