// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSiteContentRepository is an autogenerated mock type for the SiteContentRepository type
type MockSiteContentRepository struct {
	mock.Mock
}

type MockSiteContentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSiteContentRepository) EXPECT() *MockSiteContentRepository_Expecter {
	return &MockSiteContentRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx
func (_m *MockSiteContentRepository) Get(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiteContentRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSiteContentRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSiteContentRepository_Expecter) Get(ctx interface{}) *MockSiteContentRepository_Get_Call {
	return &MockSiteContentRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockSiteContentRepository_Get_Call) Run(run func(ctx context.Context)) *MockSiteContentRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSiteContentRepository_Get_Call) Return(_a0 []byte, _a1 error) *MockSiteContentRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiteContentRepository_Get_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockSiteContentRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, data
func (_m *MockSiteContentRepository) Upsert(ctx context.Context, data []byte) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiteContentRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockSiteContentRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockSiteContentRepository_Expecter) Upsert(ctx interface{}, data interface{}) *MockSiteContentRepository_Upsert_Call {
	return &MockSiteContentRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, data)}
}

func (_c *MockSiteContentRepository_Upsert_Call) Run(run func(ctx context.Context, data []byte)) *MockSiteContentRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockSiteContentRepository_Upsert_Call) Return(_a0 error) *MockSiteContentRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiteContentRepository_Upsert_Call) RunAndReturn(run func(context.Context, []byte) error) *MockSiteContentRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSiteContentRepository creates a new instance of MockSiteContentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSiteContentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSiteContentRepository {
	mock := &MockSiteContentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
