// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// IsRevoked provides a mock function with given fields: ctx, jti
func (_m *MockTokenRepository) IsRevoked(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type MockTokenRepository_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockTokenRepository_Expecter) IsRevoked(ctx interface{}, jti interface{}) *MockTokenRepository_IsRevoked_Call {
	return &MockTokenRepository_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, jti)}
}

func (_c *MockTokenRepository_IsRevoked_Call) Run(run func(ctx context.Context, jti string)) *MockTokenRepository_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_IsRevoked_Call) Return(_a0 bool, _a1 error) *MockTokenRepository_IsRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_IsRevoked_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenRepository_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// PruneExpired provides a mock function with given fields: ctx
func (_m *MockTokenRepository) PruneExpired(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PruneExpired")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_PruneExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneExpired'
type MockTokenRepository_PruneExpired_Call struct {
	*mock.Call
}

// PruneExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTokenRepository_Expecter) PruneExpired(ctx interface{}) *MockTokenRepository_PruneExpired_Call {
	return &MockTokenRepository_PruneExpired_Call{Call: _e.mock.On("PruneExpired", ctx)}
}

func (_c *MockTokenRepository_PruneExpired_Call) Run(run func(ctx context.Context)) *MockTokenRepository_PruneExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTokenRepository_PruneExpired_Call) Return(_a0 int64, _a1 error) *MockTokenRepository_PruneExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_PruneExpired_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockTokenRepository_PruneExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, jti, memberID, expiresAt
func (_m *MockTokenRepository) Revoke(ctx context.Context, jti string, memberID int64, expiresAt time.Time) error {
	ret := _m.Called(ctx, jti, memberID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, time.Time) error); ok {
		r0 = rf(ctx, jti, memberID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - memberID int64
//   - expiresAt time.Time
func (_e *MockTokenRepository_Expecter) Revoke(ctx interface{}, jti interface{}, memberID interface{}, expiresAt interface{}) *MockTokenRepository_Revoke_Call {
	return &MockTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, jti, memberID, expiresAt)}
}

func (_c *MockTokenRepository_Revoke_Call) Run(run func(ctx context.Context, jti string, memberID int64, expiresAt time.Time)) *MockTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(time.Time))
	})
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) Return(_a0 error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) RunAndReturn(run func(context.Context, string, int64, time.Time) error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
