// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/edberto/motoclub-backend/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockGoogleVerifier is an autogenerated mock type for the GoogleVerifier type
type MockGoogleVerifier struct {
	mock.Mock
}

type MockGoogleVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoogleVerifier) EXPECT() *MockGoogleVerifier_Expecter {
	return &MockGoogleVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, idToken
func (_m *MockGoogleVerifier) Verify(ctx context.Context, idToken string) (auth.GoogleIdentity, error) {
	ret := _m.Called(ctx, idToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 auth.GoogleIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (auth.GoogleIdentity, error)); ok {
		return rf(ctx, idToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) auth.GoogleIdentity); ok {
		r0 = rf(ctx, idToken)
	} else {
		r0 = ret.Get(0).(auth.GoogleIdentity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoogleVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockGoogleVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - idToken string
func (_e *MockGoogleVerifier_Expecter) Verify(ctx interface{}, idToken interface{}) *MockGoogleVerifier_Verify_Call {
	return &MockGoogleVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, idToken)}
}

func (_c *MockGoogleVerifier_Verify_Call) Run(run func(ctx context.Context, idToken string)) *MockGoogleVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGoogleVerifier_Verify_Call) Return(_a0 auth.GoogleIdentity, _a1 error) *MockGoogleVerifier_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoogleVerifier_Verify_Call) RunAndReturn(run func(context.Context, string) (auth.GoogleIdentity, error)) *MockGoogleVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoogleVerifier creates a new instance of MockGoogleVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoogleVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoogleVerifier {
	mock := &MockGoogleVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
