// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	auth "github.com/edberto/motoclub-backend/internal/auth"
	domain "github.com/edberto/motoclub-backend/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockJWTManager is an autogenerated mock type for the JWTManager type
type MockJWTManager struct {
	mock.Mock
}

type MockJWTManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTManager) EXPECT() *MockJWTManager_Expecter {
	return &MockJWTManager_Expecter{mock: &_m.Mock}
}

// IssueAccess provides a mock function with given fields: memberID, role
func (_m *MockJWTManager) IssueAccess(memberID int64, role domain.Role) (string, string, time.Time, error) {
	ret := _m.Called(memberID, role)

	if len(ret) == 0 {
		panic("no return value specified for IssueAccess")
	}

	var r0 string
	var r1 string
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(int64, domain.Role) (string, string, time.Time, error)); ok {
		return rf(memberID, role)
	}
	if rf, ok := ret.Get(0).(func(int64, domain.Role) string); ok {
		r0 = rf(memberID, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64, domain.Role) string); ok {
		r1 = rf(memberID, role)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(int64, domain.Role) time.Time); ok {
		r2 = rf(memberID, role)
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func(int64, domain.Role) error); ok {
		r3 = rf(memberID, role)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockJWTManager_IssueAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAccess'
type MockJWTManager_IssueAccess_Call struct {
	*mock.Call
}

// IssueAccess is a helper method to define mock.On call
//   - memberID int64
//   - role domain.Role
func (_e *MockJWTManager_Expecter) IssueAccess(memberID interface{}, role interface{}) *MockJWTManager_IssueAccess_Call {
	return &MockJWTManager_IssueAccess_Call{Call: _e.mock.On("IssueAccess", memberID, role)}
}

func (_c *MockJWTManager_IssueAccess_Call) Run(run func(memberID int64, role domain.Role)) *MockJWTManager_IssueAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(domain.Role))
	})
	return _c
}

func (_c *MockJWTManager_IssueAccess_Call) Return(token string, jti string, expiresAt time.Time, err error) *MockJWTManager_IssueAccess_Call {
	_c.Call.Return(token, jti, expiresAt, err)
	return _c
}

func (_c *MockJWTManager_IssueAccess_Call) RunAndReturn(run func(int64, domain.Role) (string, string, time.Time, error)) *MockJWTManager_IssueAccess_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefresh provides a mock function with given fields: memberID, role
func (_m *MockJWTManager) IssueRefresh(memberID int64, role domain.Role) (string, string, time.Time, error) {
	ret := _m.Called(memberID, role)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefresh")
	}

	var r0 string
	var r1 string
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(int64, domain.Role) (string, string, time.Time, error)); ok {
		return rf(memberID, role)
	}
	if rf, ok := ret.Get(0).(func(int64, domain.Role) string); ok {
		r0 = rf(memberID, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64, domain.Role) string); ok {
		r1 = rf(memberID, role)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(int64, domain.Role) time.Time); ok {
		r2 = rf(memberID, role)
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func(int64, domain.Role) error); ok {
		r3 = rf(memberID, role)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockJWTManager_IssueRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefresh'
type MockJWTManager_IssueRefresh_Call struct {
	*mock.Call
}

// IssueRefresh is a helper method to define mock.On call
//   - memberID int64
//   - role domain.Role
func (_e *MockJWTManager_Expecter) IssueRefresh(memberID interface{}, role interface{}) *MockJWTManager_IssueRefresh_Call {
	return &MockJWTManager_IssueRefresh_Call{Call: _e.mock.On("IssueRefresh", memberID, role)}
}

func (_c *MockJWTManager_IssueRefresh_Call) Run(run func(memberID int64, role domain.Role)) *MockJWTManager_IssueRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(domain.Role))
	})
	return _c
}

func (_c *MockJWTManager_IssueRefresh_Call) Return(token string, jti string, expiresAt time.Time, err error) *MockJWTManager_IssueRefresh_Call {
	_c.Call.Return(token, jti, expiresAt, err)
	return _c
}

func (_c *MockJWTManager_IssueRefresh_Call) RunAndReturn(run func(int64, domain.Role) (string, string, time.Time, error)) *MockJWTManager_IssueRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function with given fields: token
func (_m *MockJWTManager) Parse(token string) (auth.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (auth.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) auth.Claims); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(auth.Claims)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTManager_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockJWTManager_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - token string
func (_e *MockJWTManager_Expecter) Parse(token interface{}) *MockJWTManager_Parse_Call {
	return &MockJWTManager_Parse_Call{Call: _e.mock.On("Parse", token)}
}

func (_c *MockJWTManager_Parse_Call) Run(run func(token string)) *MockJWTManager_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTManager_Parse_Call) Return(_a0 auth.Claims, _a1 error) *MockJWTManager_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTManager_Parse_Call) RunAndReturn(run func(string) (auth.Claims, error)) *MockJWTManager_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTManager creates a new instance of MockJWTManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTManager {
	mock := &MockJWTManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
