// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: announcements.sql

package sqlc

import (
	"context"
	"time"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (title, description)
VALUES ($1, $2)
RETURNING id, title, description, created_at, last_updated_at, deleted_at
`

type CreateAnnouncementParams struct {
	Title       string
	Description string
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement, arg.Title, arg.Description)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, title, description, created_at, last_updated_at, deleted_at FROM announcements
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR created_at >= $1)
ORDER BY created_at DESC
`

func (q *Queries) ListAnnouncements(ctx context.Context, startFrom *time.Time) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, startFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAnnouncement = `-- name: SoftDeleteAnnouncement :execrows
UPDATE announcements
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAnnouncement(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET title = $2, description = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, description, created_at, last_updated_at, deleted_at
`

type UpdateAnnouncementParams struct {
	ID          int64
	Title       string
	Description string
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement, arg.ID, arg.Title, arg.Description)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
