// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: events.sql

package sqlc

import (
	"context"
	"time"
)

const countEvents = `-- name: CountEvents :one
SELECT count(*) FROM events
WHERE deleted_at IS NULL
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, description, event_date, location, is_public, image_link)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, event_date, location, created_at, last_updated_at, deleted_at, is_public, image_link
`

type CreateEventParams struct {
	Title       string
	Description string
	EventDate   time.Time
	Location    *string
	IsPublic    bool
	ImageLink   *string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.EventDate,
		arg.Location,
		arg.IsPublic,
		arg.ImageLink,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.EventDate,
		&i.Location,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
		&i.IsPublic,
		&i.ImageLink,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, title, description, event_date, location, created_at, last_updated_at, deleted_at, is_public, image_link FROM events
WHERE id = $1 AND deleted_at IS NULL
  AND (NOT $2::boolean OR is_public)
`

type GetEventByIDParams struct {
	ID         int64
	PublicOnly bool
}

func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.ID, arg.PublicOnly)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.EventDate,
		&i.Location,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
		&i.IsPublic,
		&i.ImageLink,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, description, event_date, location, created_at, last_updated_at, deleted_at, is_public, image_link FROM events
WHERE deleted_at IS NULL
  AND ($1::timestamptz IS NULL OR event_date >= $1)
  AND (NOT $2::boolean OR is_public)
ORDER BY event_date
`

type ListEventsParams struct {
	StartFrom  *time.Time
	PublicOnly bool
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.StartFrom, arg.PublicOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.EventDate,
			&i.Location,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.DeletedAt,
			&i.IsPublic,
			&i.ImageLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEvent = `-- name: SoftDeleteEvent :execrows
UPDATE events
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEvent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, description = $3, event_date = $4, location = $5, is_public = $6, image_link = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, description, event_date, location, created_at, last_updated_at, deleted_at, is_public, image_link
`

type UpdateEventParams struct {
	ID          int64
	Title       string
	Description string
	EventDate   time.Time
	Location    *string
	IsPublic    bool
	ImageLink   *string
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.EventDate,
		arg.Location,
		arg.IsPublic,
		arg.ImageLink,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.EventDate,
		&i.Location,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
		&i.IsPublic,
		&i.ImageLink,
	)
	return i, err
}
