// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: members.sql

package sqlc

import (
	"context"
	"time"
)

const backfillGoogleSub = `-- name: BackfillGoogleSub :one
UPDATE members
SET google_sub = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, google_sub, email, name, phone_number, place_of_birth, date_of_birth, address, instagram_username, blood_type, emergency_contact_name, emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path, role, status, remarks, approved_at, created_at, last_updated_at, deleted_at
`

type BackfillGoogleSubParams struct {
	ID        int64
	GoogleSub string
}

func (q *Queries) BackfillGoogleSub(ctx context.Context, arg BackfillGoogleSubParams) (Member, error) {
	row := q.db.QueryRow(ctx, backfillGoogleSub, arg.ID, arg.GoogleSub)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.PlaceOfBirth,
		&i.DateOfBirth,
		&i.Address,
		&i.InstagramUsername,
		&i.BloodType,
		&i.EmergencyContactName,
		&i.EmergencyContactPhoneNumber,
		&i.MotorbikeName,
		&i.MotorbikeSelfieLinkPath,
		&i.Role,
		&i.Status,
		&i.Remarks,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM members
WHERE deleted_at IS NULL
`

func (q *Queries) CountMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingRegistrations = `-- name: CountPendingRegistrations :one
SELECT count(*) FROM members
WHERE status = 'PENDING_APPROVAL' AND deleted_at IS NULL
`

func (q *Queries) CountPendingRegistrations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRegistrations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuperadmins = `-- name: CountSuperadmins :one
SELECT count(*) FROM members
WHERE role = 'superadmin' AND deleted_at IS NULL
`

func (q *Queries) CountSuperadmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuperadmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (
    google_sub, email, name, phone_number, place_of_birth, date_of_birth,
    address, instagram_username, blood_type, emergency_contact_name,
    emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, google_sub, email, name, phone_number, place_of_birth, date_of_birth, address, instagram_username, blood_type, emergency_contact_name, emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path, role, status, remarks, approved_at, created_at, last_updated_at, deleted_at
`

type CreateMemberParams struct {
	GoogleSub                   string
	Email                       string
	Name                        string
	PhoneNumber                 string
	PlaceOfBirth                string
	DateOfBirth                 time.Time
	Address                     string
	InstagramUsername           string
	BloodType                   string
	EmergencyContactName        string
	EmergencyContactPhoneNumber string
	MotorbikeName               string
	MotorbikeSelfieLinkPath     string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.PhoneNumber,
		arg.PlaceOfBirth,
		arg.DateOfBirth,
		arg.Address,
		arg.InstagramUsername,
		arg.BloodType,
		arg.EmergencyContactName,
		arg.EmergencyContactPhoneNumber,
		arg.MotorbikeName,
		arg.MotorbikeSelfieLinkPath,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.PlaceOfBirth,
		&i.DateOfBirth,
		&i.Address,
		&i.InstagramUsername,
		&i.BloodType,
		&i.EmergencyContactName,
		&i.EmergencyContactPhoneNumber,
		&i.MotorbikeName,
		&i.MotorbikeSelfieLinkPath,
		&i.Role,
		&i.Status,
		&i.Remarks,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT id, google_sub, email, name, phone_number, place_of_birth, date_of_birth, address, instagram_username, blood_type, emergency_contact_name, emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path, role, status, remarks, approved_at, created_at, last_updated_at, deleted_at FROM members
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMemberByEmail(ctx context.Context, email string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByEmail, email)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.PlaceOfBirth,
		&i.DateOfBirth,
		&i.Address,
		&i.InstagramUsername,
		&i.BloodType,
		&i.EmergencyContactName,
		&i.EmergencyContactPhoneNumber,
		&i.MotorbikeName,
		&i.MotorbikeSelfieLinkPath,
		&i.Role,
		&i.Status,
		&i.Remarks,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemberByGoogleSub = `-- name: GetMemberByGoogleSub :one
SELECT id, google_sub, email, name, phone_number, place_of_birth, date_of_birth, address, instagram_username, blood_type, emergency_contact_name, emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path, role, status, remarks, approved_at, created_at, last_updated_at, deleted_at FROM members
WHERE google_sub = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMemberByGoogleSub(ctx context.Context, googleSub string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByGoogleSub, googleSub)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.PlaceOfBirth,
		&i.DateOfBirth,
		&i.Address,
		&i.InstagramUsername,
		&i.BloodType,
		&i.EmergencyContactName,
		&i.EmergencyContactPhoneNumber,
		&i.MotorbikeName,
		&i.MotorbikeSelfieLinkPath,
		&i.Role,
		&i.Status,
		&i.Remarks,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, google_sub, email, name, phone_number, place_of_birth, date_of_birth, address, instagram_username, blood_type, emergency_contact_name, emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path, role, status, remarks, approved_at, created_at, last_updated_at, deleted_at FROM members
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMemberByID(ctx context.Context, id int64) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.PlaceOfBirth,
		&i.DateOfBirth,
		&i.Address,
		&i.InstagramUsername,
		&i.BloodType,
		&i.EmergencyContactName,
		&i.EmergencyContactPhoneNumber,
		&i.MotorbikeName,
		&i.MotorbikeSelfieLinkPath,
		&i.Role,
		&i.Status,
		&i.Remarks,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, google_sub, email, name, phone_number, place_of_birth, date_of_birth, address, instagram_username, blood_type, emergency_contact_name, emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path, role, status, remarks, approved_at, created_at, last_updated_at, deleted_at FROM members
WHERE deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.GoogleSub,
			&i.Email,
			&i.Name,
			&i.PhoneNumber,
			&i.PlaceOfBirth,
			&i.DateOfBirth,
			&i.Address,
			&i.InstagramUsername,
			&i.BloodType,
			&i.EmergencyContactName,
			&i.EmergencyContactPhoneNumber,
			&i.MotorbikeName,
			&i.MotorbikeSelfieLinkPath,
			&i.Role,
			&i.Status,
			&i.Remarks,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRegistrations = `-- name: ListPendingRegistrations :many
SELECT id, name, email, created_at FROM members
WHERE status = 'PENDING_APPROVAL' AND deleted_at IS NULL
ORDER BY created_at
`

type ListPendingRegistrationsRow struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) ListPendingRegistrations(ctx context.Context) ([]ListPendingRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRegistrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRegistrationsRow{}
	for rows.Next() {
		var i ListPendingRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMember = `-- name: SoftDeleteMember :execrows
UPDATE members
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMember(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE members
SET role = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, google_sub, email, name, phone_number, place_of_birth, date_of_birth, address, instagram_username, blood_type, emergency_contact_name, emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path, role, status, remarks, approved_at, created_at, last_updated_at, deleted_at
`

type UpdateMemberRoleParams struct {
	ID   int64
	Role string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.ID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.PlaceOfBirth,
		&i.DateOfBirth,
		&i.Address,
		&i.InstagramUsername,
		&i.BloodType,
		&i.EmergencyContactName,
		&i.EmergencyContactPhoneNumber,
		&i.MotorbikeName,
		&i.MotorbikeSelfieLinkPath,
		&i.Role,
		&i.Status,
		&i.Remarks,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :one
UPDATE members
SET status = $2, remarks = $3, approved_at = $4, role = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, google_sub, email, name, phone_number, place_of_birth, date_of_birth, address, instagram_username, blood_type, emergency_contact_name, emergency_contact_phone_number, motorbike_name, motorbike_selfie_link_path, role, status, remarks, approved_at, created_at, last_updated_at, deleted_at
`

type UpdateMemberStatusParams struct {
	ID         int64
	Status     string
	Remarks    *string
	ApprovedAt *time.Time
	Role       string
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberStatus,
		arg.ID,
		arg.Status,
		arg.Remarks,
		arg.ApprovedAt,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.PlaceOfBirth,
		&i.DateOfBirth,
		&i.Address,
		&i.InstagramUsername,
		&i.BloodType,
		&i.EmergencyContactName,
		&i.EmergencyContactPhoneNumber,
		&i.MotorbikeName,
		&i.MotorbikeSelfieLinkPath,
		&i.Role,
		&i.Status,
		&i.Remarks,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
