// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Announcement struct {
	ID            int64
	Title         string
	Description   string
	CreatedAt     time.Time
	LastUpdatedAt time.Time
	DeletedAt     *time.Time
	IsPublic      bool
}

type Event struct {
	ID            int64
	Title         string
	Description   string
	EventDate     time.Time
	Location      *string
	CreatedAt     time.Time
	LastUpdatedAt time.Time
	DeletedAt     *time.Time
	IsPublic      bool
}

type Gallery struct {
	ID            int64
	Link          string
	CreatedAt     time.Time
	LastUpdatedAt time.Time
	DeletedAt     *time.Time
	IsPublic      bool
}

type Member struct {
	ID                          int64
	GoogleSub                   string
	Email                       string
	Name                        string
	PhoneNumber                 string
	PlaceOfBirth                string
	DateOfBirth                 time.Time
	Address                     string
	InstagramUsername           string
	BloodType                   string
	EmergencyContactName        string
	EmergencyContactPhoneNumber string
	MotorbikeName               string
	MotorbikeSelfieLinkPath     string
	Role                        string
	Status                      string
	Remarks                     *string
	ApprovedAt                  *time.Time
	CreatedAt                   time.Time
	LastUpdatedAt               time.Time
	DeletedAt                   *time.Time
}

type RevokedToken struct {
	Jti           string
	MemberID      int64
	ExpiresAt     time.Time
	CreatedAt     time.Time
	LastUpdatedAt time.Time
	DeletedAt     *time.Time
}
