// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	BackfillGoogleSub(ctx context.Context, arg BackfillGoogleSubParams) (Member, error)
	CountPendingRegistrations(ctx context.Context) (int64, error)
	CountSuperadmins(ctx context.Context) (int64, error)
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateGalleryItem(ctx context.Context, arg CreateGalleryItemParams) (Gallery, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error)
	GetMemberByEmail(ctx context.Context, email string) (Member, error)
	GetMemberByGoogleSub(ctx context.Context, googleSub string) (Member, error)
	GetMemberByID(ctx context.Context, id int64) (Member, error)
	IsTokenRevoked(ctx context.Context, jti string) (bool, error)
	ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListGallery(ctx context.Context, publicOnly bool) ([]Gallery, error)
	ListMembers(ctx context.Context) ([]Member, error)
	ListPendingRegistrations(ctx context.Context) ([]ListPendingRegistrationsRow, error)
	PruneExpiredTokens(ctx context.Context) (int64, error)
	RevokeToken(ctx context.Context, arg RevokeTokenParams) error
	SoftDeleteAnnouncement(ctx context.Context, id int64) (int64, error)
	SoftDeleteEvent(ctx context.Context, id int64) (int64, error)
	SoftDeleteGalleryItem(ctx context.Context, id int64) (int64, error)
	SoftDeleteMember(ctx context.Context, id int64) (int64, error)
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateGalleryItem(ctx context.Context, arg UpdateGalleryItemParams) (Gallery, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (Member, error)
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (Member, error)
}

var _ Querier = (*Queries)(nil)
