// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: site_content.sql

package sqlc

import (
	"context"
)

const getSiteContent = `-- name: GetSiteContent :one
SELECT data FROM site_content WHERE id = 1
`

func (q *Queries) GetSiteContent(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSiteContent)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const upsertSiteContent = `-- name: UpsertSiteContent :exec
INSERT INTO site_content (id, data, last_updated_at)
VALUES (1, $1, now())
ON CONFLICT (id) DO UPDATE
SET data = EXCLUDED.data, last_updated_at = now()
`

func (q *Queries) UpsertSiteContent(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, upsertSiteContent, data)
	return err
}
