// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tokens.sql

package sqlc

import (
	"context"
	"time"
)

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS (
    SELECT 1 FROM revoked_tokens WHERE jti = $1
) AS revoked
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenRevoked, jti)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const revokeToken = `-- name: RevokeToken :exec
INSERT INTO revoked_tokens (jti, member_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (jti) DO NOTHING
`

type RevokeTokenParams struct {
	Jti       string
	MemberID  int64
	ExpiresAt time.Time
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.Exec(ctx, revokeToken, arg.Jti, arg.MemberID, arg.ExpiresAt)
	return err
}
