// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRevocationChecker is an autogenerated mock type for the RevocationChecker type
type MockRevocationChecker struct {
	mock.Mock
}

type MockRevocationChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRevocationChecker) EXPECT() *MockRevocationChecker_Expecter {
	return &MockRevocationChecker_Expecter{mock: &_m.Mock}
}

// IsRevoked provides a mock function with given fields: ctx, jti
func (_m *MockRevocationChecker) IsRevoked(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRevocationChecker_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type MockRevocationChecker_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockRevocationChecker_Expecter) IsRevoked(ctx interface{}, jti interface{}) *MockRevocationChecker_IsRevoked_Call {
	return &MockRevocationChecker_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, jti)}
}

func (_c *MockRevocationChecker_IsRevoked_Call) Run(run func(ctx context.Context, jti string)) *MockRevocationChecker_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRevocationChecker_IsRevoked_Call) Return(_a0 bool, _a1 error) *MockRevocationChecker_IsRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRevocationChecker_IsRevoked_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRevocationChecker_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRevocationChecker creates a new instance of MockRevocationChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRevocationChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRevocationChecker {
	mock := &MockRevocationChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
